//Game Tables

export const GET_ALL_GAMETABLES_SUCCESS = 'GET_ALL_GAMETABLES_SUCCESS';

//Socket
export const CONNECT_AUTHORIZED_SOCKET = 'CONNECT_AUTHORIZED_SOCKET';
export const CONNECT_UNAUTHORIZED_SOCKET = 'CONNECT_UNAUTHORIZED_SOCKET';

// Users

export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

//Poker

//GameState
export const GET_GAMESTATE_SUCCESS = 'GET_GAMESTATE_SUCCESS';

